Codm/urls.py
from django.urls import re_path, path
from . import views
from uuid import uuid1
app_name = 'Codm'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/(?P<page>[0-9]{1,5})$', views.ListView, name="Game"),
    #path('<str:gr>/Accounts/Page<int:page>/', views.ListView, name="codm"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/detail/(?P<co>[0-9]{1,5})/$', views.account, name="account"),
    path('<str:co>/Accounts/publish-account/', views.publish, name="publish-account"),
]

Products/urls.py
from django.urls import URLPattern, path, include, re_path
from . import views

app_name = 'Products'

urlpatterns = [
    path('view/Our-Products/<str:pname>/', views.ProductView, name="PV"),
    path('view/Our-Products/addtocart/<str:pname>/<int:pcode>/', views.ProductAddCart, name="PAC"),
    path('view/Our-Products/removefromcart/<str:pname>/<int:pcode>/', views.ProductRemoveCart, name="PRC"),
]

TSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Codm.urls')),
    path('user/', include('Users.urls')),
    path('products/', include('Products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import re_path
from . import views
from uuid import uuid1
app_name = 'Users'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^login/$', views.LoginFunc, name="login"),
    re_path(r'^logout/$', views.LogoutFunc, name="logout"),
    re_path(r'^registration/$', views.RegisterFunc, name="signup"),
    re_path(r'^welcome/$', views.WelcomeFunc, name="welcome"),

    re_path(r'^cart/details/$', views.user_cart, name="cart"),
    re_path(r'^cart/continue/UserInfo/$', views.cart_continue, name="cart_continue"),
    re_path(r'^cart/continue/UserInfo/SelectAccount/(?P<pr>[0-9]{1,10})/(?P<pk>[0-9]{1,10})$', views.add_account_product, name="add_account_product"),
    re_path(r'^cart/all/cart-end/success/{}/{}/$'.format(id1, id2), views.cart_success, name="cart-success"),
    re_path(r'^cart/success/finished/order/(?P<order>[0-9]{1,10})/(?P<order1>[0-9]{1,10})$', views.cart_finished, name="cart-finished"),
    re_path(r'^cart/details/shopping/render/ok$', views.shopping, name="shopping"),
    re_path(r'^addtocart/account/(?P<co>[0-9]{1,5})/$', views.addtocart, name="addtocart"),
    re_path(r'^removefromcart/account/(?P<co>[0-9]{1,5})/$', views.removefromcart, name="removefromcart"),

    re_path(r'^MyAccount/$', views.user_panel, name="UserPanel"),
    re_path(r'^MyAccount/Myinfo/Edit/$', views.user_edit, name="UserEdit"),
    re_path(r'^MyAccount/Orders/$', views.user_orders, name="UserOrders"),
    re_path(r'^MyAccount/Orders/OrderDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderDetail, name="UserOrderDetail"),
    re_path(r'^MyAccount/Orders/OrderAccountDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderAccountDetail, name="UserOrderAccountDetail"),
    re_path(r'^MyAccount/Accounts/$', views.user_accounts, name="UserAccounts"),
    re_path(r'^MyAccount/Accounts/DeleteAccount/(?P<co>[0-9]{1,5})/$', views.user_delete_account, name="UserAccountDelete"),

    re_path(r'^SiteTheme/(?P<mode>[a-z]{1,10})/$', views.site_mode, name="ChangeMode"),
]

Users/forms.py
from django import forms
from django.forms import ModelForm, widgets
from phonenumber_field.formfields import PhoneNumberField
from Codm import models
from . import models

class UserCreationForm(ModelForm):
    class Meta:
        model = models.User
        fields = ['name', 'username', 'phone', 'email', 'password']
        labels = {
            'name' : 'نام',
            'username' : 'نام کاربری',
            'phone' : 'تلفن همراه',
            'email' : 'ایمیل',
            'password' : 'رمز',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class':'input-ui pr-2'}),
            'username' : forms.TextInput(attrs={'class' : 'input-ui pr-2'}), 
            'phone' : forms.TextInput(attrs={'class' : 'input-ui pl-2 text-left dir-ltr'}),
            'email' : forms.EmailInput(attrs={'class':'input-ui pl-2 text-left dir-ltr'}),
        }

class UserEditionForm(ModelForm):
    class Meta:
        model = models.User
        fields = ['name', 'phone', 'email']
        labels = {
            'name' : 'نام',
            'phone' : 'تلفن همراه',
            'email' : 'ایمیل',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class':'input-ui pr-2'}),
            'phone' : forms.TextInput(attrs={'class' : 'input-ui pl-2 text-left dir-ltr'}),
            'email' : forms.EmailInput(attrs={'class':'input-ui pl-2 text-left dir-ltr'}),
        }

Users/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from Users.models import User
from Products.models import EP, Product
from Codm.models import Cart, Order, Account, Banner, OrderAccount
from .forms import UserCreationForm, UserEditionForm
from random import randint
from datetime import date
from django.contrib import messages
from time import sleep

def LoginFunc(request):
    if request.user.is_authenticated:
        return redirect('Users:UserPanel')
    Page = 'login'
    message = None
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        try: 
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'ایمیل و رمز وارد شده اشتباه است.')
        else:
            USER = authenticate(request, email=email, password=password)

            if USER:
                login(request, USER)
                messages.success(request, 'شما وارد شدید.')
                return redirect(request.META.get('HTTP_REFERER', '/'))
            else:
                messages.error(request, 'ایمیل و رمز وارد شده اشتباه است.')
    final_message = message if message != None else ''
    context = {
        'message' : final_message,
        'Page' : Page,
    }
    return render(request, 'login.html', context)

@login_required(login_url='Users:login')
def LogoutFunc(request):
    logout(request)
    messages.success(request, 'شما از حساب کاربری خود خارج شده اید.')
    return redirect('Codm:home')

def RegisterFunc(request):
    user_form = UserCreationForm()
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            cart = Cart(user=user, status='fn')
            cart.save()
            login(request, user)
            message = "You Successfully logged in!"
            return redirect('Users:welcome')
    return render(request, 'signup.html', {'form' : user_form})

def WelcomeFunc(request):
    if request.user.is_authenticated:
        return render(request, 'welcome.html', {'user': request.user})
    else:
        return redirect('Users:login')

@login_required(login_url='Users:login')
def user_cart(request):
    cart = request.user.cart
    cart.save()

    cart_account = request.user.cart.account.all()
    cart_product = request.user.cart.product.all()

    for naccount in cart_account:
        if naccount.status != 'available':
            cart.final_price -= naccount.price
            cart.account.remove(naccount)
            cart.save()
            messages.error(request, 'اکانت به شماره آگهی {} قبل از نهایی شدن خرید شما فروخته یا پاک شد و بنابراین از سبد خرید شما حذف شد'.format(naccount.code))
    for nproduct in cart_product:
        if nproduct.status != 'AV':
            cart.final_price -= nproduct.price
            cart.product.remove(nproduct)
            cart.save()
            messages.error(request, 'محصول {} .دیگر موجود نیست و از سبد خرید شما حذف شد'.format(nproduct.name))      
    if cart.account.exists() or cart.product.exists():
        cart_account = request.user.cart.account.all()
        cart_product = request.user.cart.product.all()
        cart_n = cart_account.count() + cart_product.count()
        cart.save()

        cart_object_sum = 0
        for account in cart_account:
            cart_object_sum += account.price
        for product in cart_product:
            cart_object_sum += product.price
        if cart.final_price != cart_object_sum:
            if cart_object_sum != 0:
                cart.final_price = cart_object_sum
                cart.save()

        context = {
            'cart' : cart,
            'cart_account' : cart_account,
            'cart_product' : cart_product,
            'n' : cart_n,
            'page' : 'cart'
        }
        return render(request, 'cart.html', context)
    else:
        banners = Banner.objects.filter(show__exact=True).order_by('-code')
        small_banners = banners.filter(Type__exact='smallbanner')[:4]
        random_products = Product.objects.filter(status__exact='AV').order_by('?')[:10]
        random_accounts = Account.objects.filter(status__exact='available').order_by('?')[:10]
        context = {
            'random_products' : random_products,
            'random_accounts' : random_accounts,
            'small_banners' : small_banners
        }
        return render(request, 'cart-empty.html', context)

@login_required(login_url='Users:login')
def cart_continue(request):
    cart = request.user.cart
    cart_account = request.user.cart.account.all()
    cart_product = request.user.cart.product.all()
    eps = request.user.ep_set.all()

    for naccount in cart_account:
        if naccount.status != 'available':
            cart.final_price -= naccount.price
            cart.account.remove(naccount)
            cart.save()
            messages.error(request, 'اکانت به شماره آگهی {} قبل از نهایی شدن خرید شما فروخته یا پاک شد و بنابراین از سبد خرید شما حذف شد'.format(naccount.code))
            return redirect('Users:cart')
    for nproduct in cart_product:
        if nproduct.status != 'AV':
            cart.final_price -= nproduct.price
            cart.product.remove(nproduct)
            cart.save()
            messages.error(request, 'محصول {} .دیگر موجود نیست و از سبد خرید حذف شد'.format(nproduct.name))
            return redirect('Users:cart')
    if cart.account.exists() or cart.product.exists():
        if request.method == 'POST':
            Type = request.POST.get('type')
            email = request.POST.get('email')
            password = request.POST.get('password')
            ep = EP(user=request.user, Type=Type, email=email, password=password)
            ep.save()
            return redirect('Users:cart_continue')


        context = {
            'cart' : cart,
            'cart_accounts' : cart_account,
            'cart_products' : cart_product,
            'EPs' : eps,
        }
        return render(request, 'shopping.html', context)
    else:
        return redirect('Users:cart')

@login_required(login_url='Users:login')
def add_account_product(request, pk, pr):
    ep = EP.objects.get(pk=pk)
    product = Product.objects.get(pk=pr)
    product.ep.add(ep)
    product.save()
    return redirect('Users:cart_continue')

@login_required(login_url='Users:login')
def cart_success(request):
    cart = request.user.cart
    if cart.status != 'f':
        return redirect('Users:cart')
    else:
        order = None
        order1 = None
        if cart.product.exists():
            order = Order(user=request.user, order_number=randint(10000, 20000),
            factor_number=randint(20000, 30000), date=date.today())
            order.save()
        if cart.account.exists():
            order1 = OrderAccount(user=request.user, order_number=randint(10000, 20000),
            factor_number=randint(20000, 30000), date=date.today())
            order1.save()

        cart_account = request.user.cart.account.all()
        cart_product = request.user.cart.product.all()

        for account in cart_account:
            account.status = 'sold'
            account.order = order1
            seller = User.objects.get(email=account.seller.email)
            seller.sells += 1
            seller.save()
            account.save()
            request.user.buys += 1
            request.user.save()
            order1.final_price += account.price
        if order1:
            order1.status = 'w4a'
            order1.save()
        #code ersal payam inja
        for product in cart_product:
            order.product.add(product)
            order.save()
            request.user.buys += 1
            request.user.save()
            order.final_price += product.price
        order.save() if order else None
        #code ersal payam inja
        
        final_price = cart.final_price
        cart.delete()
        new_cart = Cart(user=request.user, status='fn')
        new_cart.save()
        if order and order1:
            return redirect('Users:cart-finished', order.order_number, order1.order_number,)
        elif order:
            none = 111
            return redirect('Users:cart-finished', order.order_number, none,)
        else:
            none = 222
            return redirect('Users:cart-finished', order1.order_number, none,)


@login_required(login_url='Users:login')
def cart_finished(request, order, order1):
    random_products = Product.objects.filter(status__exact='AV').order_by('?')[:10]
    if order1 == '111':
        if order != '111':
            user_order = Order.objects.get(order_number=order)
            if user_order.status == 'w4c':
                product = True
                context = {
                    'order' : user_order,
                    'product' : product,
                    'random_products' : random_products,
                }
                return render(request, 'shopping-complete.html', context)
    elif order1 == '222':
        if order != '111':
            user_order = OrderAccount.objects.get(order_number=order)
            if user_order.status == 'w4a':
                product = False
                context = {
                    'order' : user_order,
                    'product' : product,
                    'random_products' : random_products,
                }
                return render(request, 'shopping-complete.html', context)
    else:
        if order != '111':
            user_order = Order.objects.get(order_number=order)
            user_order1 = OrderAccount.objects.get(order_number=order1)
            if user_order.status == 'w4c':
                product = True

Users/templates/cart-success.html
{% extends 'Codm/base.html' %}

{% block content %}
<div style="position:absolute; top: 50%;">
{{order.date}}<br />
{{order.order_number}}<br />
{{order.factor_number}}<br />

{% for account in order_accounts %}
کد اکانت:{{account.code}}<br />
فروشنده:{{account.seller.username}}<br />
قیمت:{{account.price}}<br />
{% endfor %}
{{cart.status}}<br />
</div>
{% endblock %}

Users/templates/cart.html
{% extends 'Codm/base.html' %}
{% load static %}
{% load jalali_tags %}

{% block content %}
<title>GameStore | UserCart</title>
<!-- Start main-content -->
<main class="main-content dt-sl mb-3">
    <div class="container main-container">
        <div class="row mx-0">
            <div class="col-xl-9 col-lg-8 col-md-12 col-sm-12 mb-2">
                <nav class="tab-cart-page">
                    <div class="nav nav-tabs border-bottom" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link d-inline-flex w-auto active" id="nav-home-tab"
                            data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home"
                            aria-selected="true">سبد خرید شما<span class="count-cart">{{n}}</span></a>
                    </div>
                </nav>
            </div>
            <div class="col-12">
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                        aria-labelledby="nav-home-tab">
                        <div class="row">
                            <div class="col-xl-9 col-lg-8 col-12 px-0">
                                <div class="table-responsive checkout-content dt-sl">
                                    <div class="checkout-header checkout-header--express">
                                        <span class="checkout-header-title">سبد خرید</span>
                                        <span class="checkout-header-extra-info">({{n}} کالا)</span>
                                    </div>
                                    <table class="table table-cart">
                                        <tbody>
                                            {% if cart_account %}
                                            {% for account in cart_account %}
                                            <tr class="checkout-item border-bottom">
                                                <td>
                                                    {% if account.picture %}
                                                    <img src="{{ account.picture.url }}" alt=""
                                                    style="width:200px; height: 150px;object-fit: cover; object-position: center; border-radius: 5px;">
                                                    {% else %}
                                                    <img src="{% static 'assets/img/banner/codm1.jpg' %}" alt=""
                                                    style="width:200px; height: 150px;object-fit: cover; object-position: center; border-radius: 5px;">
                                                    {% endif %}
                                                    <a href="{% url 'Users:removefromcart' account.code %}" /><button class="checkout-btn-remove" >&times;</button></a>
                                                </td>
                                                <td class="text-right">
                                                    <a href="#">
                                                        <h3 class="checkout-title">
                                                            کد آگهی: {{account.code}}
                                                        </h3>
                                                    </a>
                                                    <p class="checkout-dealer">
                                                        فروشنده: {{account.seller}}@
                                                    </p>
                                                    <p class="checkout-dealer">
                                                        تاریخ انتشار: 14{{account.pub_date|to_jalali:'%y/%m/%d'}}
                                                    </p>
                                                    <p class="checkout-guarantee"></p>
                                                    <div class="checkout-variant checkout-variant--color">
                                                        <span class="checkout-variant-title">دسته :</span>
                                                        {{account.group}}
                                                    </div>
                                                </td>
                                                <td>
                                                </td>
                                                <td><strong> قیمت: {{account.price}} تومان</strong></td>
                                            </tr>
                                            {% endfor %}
                                            {% endif %}


                                            {% if cart_product %}
                                            {% for product in cart_product %}
                                            <tr class="checkout-item border-bottom">
                                                <td>
                                                    {% if product.image %}
                                                    <img src="{{ product.image.url }}" alt=""
                                                    style="width:200px; height: 150px;object-fit: cover; object-position: center; border-radius: 5px;">
                                                    {% else %}
                                                    <img src="{% static 'assets/img/banner/codm1.jpg' %}" alt=""
                                                    style="width:200px; height: 150px;object-fit: cover; object-position: center; border-radius: 5px;">
                                                    {% endif %}
                                                    <a href="{% url 'Products:PRC' product.group.tag product.code %}"<button class="checkout-btn-remove">&times;</button>
                                                </td>
                                                <td class="text-right">
                                                    <a href="#">
                                                        <h3 class="checkout-title">
                                                            نام کالا: {{product.name}}
                                                        </h3>
                                                    </a>
                                                    <p class="checkout-dealer">
                                                        فروشنده: GameStore
                                                    </p>
                                                    <p class="checkout-guarantee"></p>
                                                    <div class="checkout-variant checkout-variant--color">
                                                        <span class="checkout-variant-title">دسته :</span>
                                                        {{product.group}}
                                                    </div>
                                                </td>
                                                <td>
                                                </td>
                                                <td><strong> قیمت: {{product.price}} تومان</strong></td>
                                            </tr>
                                            {% endfor %}
                                            {% endif %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-4 col-12 w-res-sidebar sticky-sidebar">
                                <div class="dt-sn dt-sn--box border mb-2">
                                    <ul class="checkout-summary-summary">
                                        <li>
                                            <span>مبلغ کل ({{n}} کالا)</span><span>{{cart.final_price}} تومان</span>
                                        </li>
                                        <li class="checkout-summary-discount">
                                            <span>سود شما از خرید</span><span><span>(x٪)</span>y
                                                تومان</span>
                                        </li>
                                        <li class="checkout-club-container">
                                            <span>سابقه خرید شما از سایت<span class="help-sn" data-toggle="tooltip"
                                                    data-html="true" data-placement="bottom"
                                                    title="<div class='help-container is-right'><div class='help-arrow'></div><p class='help-text'>با افزایش سابقه خرید و فروش در سایت، می توانید مشمول دریافت هدایا و امکانات بیشتر در سایت شوید.</p></div>">
                                                    <span class="mdi mdi-information-outline"></span>
                                                </span></span><span><span>{{n}}+</span></span>
                                        </li>
                                    </ul>
                                    <div class="checkout-summary-devider">
                                        <div></div>
                                    </div>
                                    <div class="checkout-summary-content">
                                        <div class="checkout-summary-price-title">مبلغ قابل پرداخت:</div>
                                        <div class="checkout-summary-price-value">
                                            <span class="checkout-summary-price-value-amount">{{cart.final_price}}</span>
                                            تومان
                                        </div>
                                        <a href="{% url 'Users:cart_continue' %}" class="mb-2 d-block">
                                            <button class="btn-primary-cm btn-with-icon w-100 text-center pr-0">
                                                <i class="mdi mdi-arrow-left"></i>
                                                ادامه ثبت سفارش
                                            </button>
                                        </a>
                                        <div>
                                            <span>
                                                کالاهای موجود در سبد شما ثبت و رزرو نشده‌اند، برای ثبت سفارش
                                                مراحل بعدی را تکمیل کنید.
                                            </span><span class="help-sn" data-toggle="tooltip" data-html="true"
                                                data-placement="bottom"
                                                title="<div class='help-container is-right'><div class='help-arrow'></div><p class='help-text'>محصولات موجود در سبد خرید شما تنها در صورت ثبت و پرداخت سفارش برای شما رزرو می‌شوند. در صورت عدم ثبت سفارش، گیم استور هیچگونه مسئولیتی در قبال تغییر قیمت یا موجودی این کالاها ندارد.</p></div>">
                                                <span class="mdi mdi-information-outline"></span>
                                            </span></div>
                                    </div>
                                </div>
                                <div class="dt-sn dt-sn--box checkout-feature-aside pt-4">
                                    <ul>
                                        <li class="checkout-feature-aside-item">
                                            <img src="./assets/img/svg/return-policy.svg" alt="">
                                            هفت روز ضمانت تعویض
                                        </li>
                                        <li class="checkout-feature-aside-item">
                                            <img src="./assets/img/svg/payment-terms.svg" alt="">
                                            پرداخت در محل با کارت بانکی
                                        </li>
                                        <li class="checkout-feature-aside-item">
                                            <img src="./assets/img/svg/delivery.svg" alt="">
                                            تحویل اکسپرس
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- End main-content -->
{% endblock %}

Users/templates/cart1.html
{% extends 'Panel/panel.html' %}

{% block content %}
<div>
{% for account in cart_account %}
کد اکانت:{{account.code}}<br />
فروشنده:{{account.seller.username}}<br />
قیمت:{{account.price}}<br />
-----------------------<br />
{% endfor %}
<a href="{% url 'Users:shopping' %}"><button >ثبت نهایی و خرید</button></a>
</div>

{% endblock %}

Users/templates/login1.html
{% extends 'Codm/base.html' %}

{% block content %}
<div style="position: absolute; top:50%; left: 50%; transform: translate();">
{{uuser}}
{{message}}
{% if Page == 'login' %}
<form method="post">
    {% csrf_token %}
    <input type="email" placeholder="ایمیل خود را وارد کنید" required="true" name="email" /><br />
    <input type="password" placeholder="رمز عبور خود را وارد کنید" required="true" name="password" />
    <input type="submit" value="ورود" />
</form>
هنوز حساب کاربری ندارید؟ <a href="{% url 'Users:signup' %}">ساخت حساب</a>
{% else %}
{% endif %}
</div>
{% endblock %}

Users/templates/signup.html
<style>
    form{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        align-items: center;
        direction: rtl;
    }
</style>
<form method="post">
    <h1>ساخت حساب در گیم استور!</h1>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="ساخت حساب" /><br />
    رمز خود را فراموش کردید؟ <a href="">تغییر رمز عبور</a>
    قبلا حساب کاربری ساخته اید؟ <a href="{% url 'Users:login' %}" >ورود</a>
</form>