Codm/urls.py
from django.urls import re_path, path
from . import views
from uuid import uuid1
app_name = 'Codm'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/(?P<page>[0-9]{1,5})$', views.ListView, name="Game"),
    #path('<str:gr>/Accounts/Page<int:page>/', views.ListView, name="codm"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/detail/(?P<co>[0-9]{1,5})/$', views.account, name="account"),
    path('<str:co>/Accounts/publish-account/', views.publish, name="publish-account"),
]

Products/urls.py
from django.urls import URLPattern, path, include, re_path
from . import views

app_name = 'Products'

urlpatterns = [
    path('view/Our-Products/<str:pname>/', views.ProductView, name="PV"),
    path('view/Our-Products/addtocart/<str:pname>/<int:pcode>/', views.ProductAddCart, name="PAC"),
    path('view/Our-Products/removefromcart/<str:pname>/<int:pcode>/', views.ProductRemoveCart, name="PRC"),
]

TSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Codm.urls')),
    path('user/', include('Users.urls')),
    path('products/', include('Products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.db import models
from Users.models import User

class Group(models.Model):
    tag = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='Products/media/Products/product-logos/', max_length=5000, null=True)
    background = models.ImageField(upload_to='Products/media/Products/product-backgrounds/', max_length=5000, null=True)
    description = models.TextField(max_length=900, null=True)

    facebook = models.BooleanField(default=False)
    gmail = models.BooleanField(default=False)
    apple = models.BooleanField(default=False)
    activition = models.BooleanField(default=True)
    supercell = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class EP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    Ts = (
        ('activision' , 'اکتیویژن'),
        ('facebook' , 'فیسبوک'),
        ('gmail' , 'جیمیل'),
        ('apple' , 'اپل آی-دی'),
        ('supercell' , 'سوپرسل'),
    )
    Type = models.CharField(max_length=10, choices=Ts, default="Activision")

class Product(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    ep = models.ManyToManyField(EP, blank=True)

    code = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=900, null=True, blank=True)

    image = models.ImageField(upload_to='Products/media/Products/product_picture/{}/'.format(group.name), max_length=5000, null=True)

    S = (
        ('AV', 'Available'),
        ('NA', 'NotAvailable'),
    )
    status = models.CharField(max_length=2, choices=S, default='AV')

    price = models.IntegerField(default=30000)

    def __str__(self):
        return '{};{};{}تومان'.format(self.group, self.name, self.price)

Products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from . import models
from django.contrib.auth.decorators import login_required
from Codm.models import Cart
from django.http import HttpResponse
from django.contrib import messages

group_list = [
    'CP', 'COC', 'CR'
]
def ProductView(request, pname):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        products = group.product_set.all()

        context = {
            'group': group,
            'products': products,
        }
        return render (request, 'Products/index.html', context)

@login_required(login_url='Users:login')
def ProductAddCart(request, pname, pcode):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        product = group.product_set.get(code=pcode)
        if product:
            cart = request.user.cart
            cart.product.add(product)
            cart.final_price += product.price
            cart.save()
            messages.success(request, 'کالا به سبد خرید شما اضافه شد!')
            return redirect('Users:cart')
        else:
            messages.error(request, 'مشکلی پیش آمده! دوباره تلاش کنید')
            return redirect('Products:PV', pname)

@login_required(login_url='Users:login')
def ProductRemoveCart(request, pname, pcode):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        product = group.product_set.get(code=pcode)
        if product:
            cart = request.user.cart
            cart.final_price -= product.price
            cart.product.remove(product)
            cart.save()
            messages.success(request, 'کالا از سبد خرید شما حذف شد!')
            return redirect('Users:cart')
        else:
            messages.error(request, 'مشکلی پیش آمده! دوباره تلاش کنید')
            return redirect('Products:PV', pname)

Products/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>{{group.description}}</title>
  <meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
      <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css'><link rel="stylesheet" href="{% static 'Products/style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="wrapper">
  <div class="content">
    <div class="bg-shape">
      <img src="{% static 'Products/product_picture/cod-logo.png' %}" style="width:1757; height: 750;" alt="">
    </div>

    
    <div class="product-img">
    {% for product in products %}
      <div class="product-img__item" id="img{{product.code}}">
        <img src="{{ product.image.url }}" style="width: 400px; height:400px" alt="" class="product-img__img">
      </div>
    {% endfor %}
    </div>


    <div class="product-slider">
      <button class="prev disabled">
        <span class="icon">
          <svg class="icon icon-arrow-right"><use xlink:href="#icon-arrow-left"></use></svg>
        </span>
      </button>
      <button class="next">
        <span class="icon">
          <svg class="icon icon-arrow-right"><use xlink:href="#icon-arrow-right"></use></svg>
        </span>
      </button>

      <div class="product-slider__wrp swiper-wrapper">
        {% for product in products %}
        <div class="product-slider__item swiper-slide" data-target="img{{product.code}}">
          <div class="product-slider__card">
            <img src="{% static 'Products/product_picture/background-color.jpg' %}" alt="" style="opacity: 0.9;" class="product-slider__cover" />
            <div class="product-slider__content">
              <h1 class="product-slider__title">
                {{group.name}} <br>
                {{product.name}}
              </h1>
              <hr style="border: none; border-top: solid 1px gray;">
              <span class="product-slider__price">{{product.price}} تومان</span>
              <div class="product-ctr" style="direction: rtl;">
                <div class="product-labels">
                  <p>
                    توجه!<br />
                    {{product.description}}
                  </p>
                </div>
                <span class="hr-vertical"></span>

                <div class="product-inf">
                  <div class="product-inf__percent">
                    <div class="product-inf__percent-circle">
                      <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
                        <defs>
                          <linearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
                            <stop offset="0%" stop-color="#0c1e2c" stop-opacity="0" />
                            <stop offset="100%" stop-color="#cb2240" stop-opacity="1" />
                          </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="47" stroke-dasharray="240, 300" stroke="#D7D750" stroke-width="4" fill="none"/>
                      </svg>
                    </div>
                    <div class="product-inf__percent-txt">
                      5m
                    </div>
                  </div>

                  <span class="product-inf__title" style="font-family: 'Noto Sans Arabic', sans-serif; letter-spacing: 0;">حداقل زمان شارژ</span>
                </div>

              </div>

              <div class="product-slider__bottom">
                <a href="{% url 'Products:PAC' group.tag product.code %}">
                <button class="product-slider__cart" style="font-family: 'Noto Sans Arabic', sans-serif; letter-spacing: 0;">
                  افزودن به سبد خرید
                </button>
              </a>

                <button class="product-slider__fav js-fav" style="font-family: 'Noto Sans Arabic', sans-serif; letter-spacing: 0;"><span class="heart"></span> افزودن به علاقه مندی ها</button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
        
  </div>
</div>
<svg class="hidden" hidden>
  <symbol id="icon-arrow-left" viewBox="0 0 32 32">
    <path d="M0.704 17.696l9.856 9.856c0.896 0.896 2.432 0.896 3.328 0s0.896-2.432 0-3.328l-5.792-5.856h21.568c1.312 0 2.368-1.056 2.368-2.368s-1.056-2.368-2.368-2.368h-21.568l5.824-5.824c0.896-0.896 0.896-2.432 0-3.328-0.48-0.48-1.088-0.704-1.696-0.704s-1.216 0.224-1.696 0.704l-9.824 9.824c-0.448 0.448-0.704 1.056-0.704 1.696s0.224 1.248 0.704 1.696z"></path>
  </symbol>
  <symbol id="icon-arrow-right" viewBox="0 0 32 32">
    <path d="M31.296 14.336l-9.888-9.888c-0.896-0.896-2.432-0.896-3.328 0s-0.896 2.432 0 3.328l5.824 5.856h-21.536c-1.312 0-2.368 1.056-2.368 2.368s1.056 2.368 2.368 2.368h21.568l-5.856 5.824c-0.896 0.896-0.896 2.432 0 3.328 0.48 0.48 1.088 0.704 1.696 0.704s1.216-0.224 1.696-0.704l9.824-9.824c0.448-0.448 0.704-1.056 0.704-1.696s-0.224-1.248-0.704-1.664z"></path>
  </symbol>
</svg>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js'></script><script  src="{% static 'Products/script.js' %}"></script>

</body>
</html>