Codm/urls.py
from django.urls import re_path, path
from . import views
from uuid import uuid1
app_name = 'Codm'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/(?P<page>[0-9]{1,5})$', views.ListView, name="Game"),
    #path('<str:gr>/Accounts/Page<int:page>/', views.ListView, name="codm"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/detail/(?P<co>[0-9]{1,5})/$', views.account, name="account"),
    path('<str:co>/Accounts/publish-account/', views.publish, name="publish-account"),
]

Products/urls.py
from django.urls import URLPattern, path, include, re_path
from . import views

app_name = 'Products'

urlpatterns = [
    path('view/Our-Products/<str:pname>/', views.ProductView, name="PV"),
    path('view/Our-Products/addtocart/<str:pname>/<int:pcode>/', views.ProductAddCart, name="PAC"),
    path('view/Our-Products/removefromcart/<str:pname>/<int:pcode>/', views.ProductRemoveCart, name="PRC"),
]

TSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Codm.urls')),
    path('user/', include('Users.urls')),
    path('products/', include('Products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import re_path
from . import views
from uuid import uuid1
app_name = 'Users'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^login/$', views.LoginFunc, name="login"),
    re_path(r'^logout/$', views.LogoutFunc, name="logout"),
    re_path(r'^registration/$', views.RegisterFunc, name="signup"),
    re_path(r'^welcome/$', views.WelcomeFunc, name="welcome"),

    re_path(r'^cart/details/$', views.user_cart, name="cart"),
    re_path(r'^cart/continue/UserInfo/$', views.cart_continue, name="cart_continue"),
    re_path(r'^cart/continue/UserInfo/SelectAccount/(?P<pr>[0-9]{1,10})/(?P<pk>[0-9]{1,10})$', views.add_account_product, name="add_account_product"),
    re_path(r'^cart/all/cart-end/success/{}/{}/$'.format(id1, id2), views.cart_success, name="cart-success"),
    re_path(r'^cart/success/finished/order/(?P<order>[0-9]{1,10})/(?P<order1>[0-9]{1,10})$', views.cart_finished, name="cart-finished"),
    re_path(r'^cart/details/shopping/render/ok$', views.shopping, name="shopping"),
    re_path(r'^addtocart/account/(?P<co>[0-9]{1,5})/$', views.addtocart, name="addtocart"),
    re_path(r'^removefromcart/account/(?P<co>[0-9]{1,5})/$', views.removefromcart, name="removefromcart"),

    re_path(r'^MyAccount/$', views.user_panel, name="UserPanel"),
    re_path(r'^MyAccount/Myinfo/Edit/$', views.user_edit, name="UserEdit"),
    re_path(r'^MyAccount/Orders/$', views.user_orders, name="UserOrders"),
    re_path(r'^MyAccount/Orders/OrderDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderDetail, name="UserOrderDetail"),
    re_path(r'^MyAccount/Orders/OrderAccountDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderAccountDetail, name="UserOrderAccountDetail"),
    re_path(r'^MyAccount/Accounts/$', views.user_accounts, name="UserAccounts"),
    re_path(r'^MyAccount/Accounts/DeleteAccount/(?P<co>[0-9]{1,5})/$', views.user_delete_account, name="UserAccountDelete"),

    re_path(r'^SiteTheme/(?P<mode>[a-z]{1,10})/$', views.site_mode, name="ChangeMode"),
]

Products/models.py
from django.db import models
from Users.models import User

class Group(models.Model):
    tag = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='Products/media/Products/product-logos/', max_length=5000, null=True)
    background = models.ImageField(upload_to='Products/media/Products/product-backgrounds/', max_length=5000, null=True)
    description = models.TextField(max_length=900, null=True)

    facebook = models.BooleanField(default=False)
    gmail = models.BooleanField(default=False)
    apple = models.BooleanField(default=False)
    activition = models.BooleanField(default=True)
    supercell = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class EP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    Ts = (
        ('activision' , 'اکتیویژن'),
        ('facebook' , 'فیسبوک'),
        ('gmail' , 'جیمیل'),
        ('apple' , 'اپل آی-دی'),
        ('supercell' , 'سوپرسل'),
    )
    Type = models.CharField(max_length=10, choices=Ts, default="Activision")

class Product(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    ep = models.ManyToManyField(EP, blank=True)

    code = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=900, null=True, blank=True)

    image = models.ImageField(upload_to='Products/media/Products/product_picture/{}/'.format(group.name), max_length=5000, null=True)

    S = (
        ('AV', 'Available'),
        ('NA', 'NotAvailable'),
    )
    status = models.CharField(max_length=2, choices=S, default='AV')

    price = models.IntegerField(default=30000)

    def __str__(self):
        return '{};{};{}تومان'.format(self.group, self.name, self.price)

Codm/forms.py
from django.forms import ModelForm
from jdatetime import date
from Codm import models
#User
from django.conf import settings
User = settings.AUTH_USER_MODEL

class AccountForm(ModelForm):
    class Meta:
        model = models.Account
        fields = ['price', 'picture']

        labels = {
            'picture' : 'تصویر نمایش اکانت',
            'price' : 'قیمت'
        }

class CodAccountForm(ModelForm):
    class Meta:
        model = models.CodAccount
        fields = ['level', 'region', 'c', 'cp', 
        'multi_ranked', 'battle_ranked', 'battle_pass',
        'description']

        labels = {
            'level' : 'لول',
            'region' : 'ریجن اکانت',
            'c' : 'تعداد c اکانت',
            'cp' : 'تعداد cp اکانت',
            'multi_ranked' : 'رنک مولتی اکانت',
            'battle_ranked' : 'رنک بتل اکانت',
            'battle_pass' : 'بتل پس های اکانت',
            'description' : 'سایر توضیحات شما',
        }

class AccountVideoForm(ModelForm):
    class Meta:
        model = models.Video
        fields = [
            'video',
        ]
        labels = {
            'video' : 'ویدیو اکانت'
        }

class AccountLinkForm(ModelForm):
    class Meta:
        model = models.Link
        fields = [
            'Type',
        ]
        labels = {
            'Type' : 'سیو اکانت'
        }

class AccountImageForm(ModelForm):
    class Meta:
        model = models.Image
        fields = [
            'image',
        ]
        labels = {
            'image' : 'سایر تصاویر اکانت'
        }


'''class UserCreationForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'name', 'username', 'phone', 'email', 'password'
        ]'''

Codm/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from Products.models import Product
from . import models
from django.contrib import messages
from Codm.models import Order, Cart, Video
from django.db.models import Q
from Codm.forms import AccountForm, AccountLinkForm, CodAccountForm, AccountImageForm, AccountVideoForm
from django.http import Http404
#User Login
from django.contrib.auth.decorators import login_required
from django.conf import settings
User1 = settings.AUTH_USER_MODEL
from Users.models import User
#random
from random import randint

def home(request):
    sliders = models.Slider.objects.filter(show__exact=True)
    sliders_count = sliders.count()

    responsivesliders = models.ResponsiveSlider.objects.filter(show__exact=True)
    responsivesliders_count = responsivesliders.count()

    banners = models.Banner.objects.filter(show__exact=True).order_by('-code')
    banners_count = banners.count()

    middle_banner= banners.filter(Type__exact='middlebanner')[:2]
    small_banner = banners.filter(Type__exact='smallbanner')[:4]

    accounts = models.Account.objects.filter(status__exact='available', group__exact='codm').order_by('-code')[:10]
    random_products = Product.objects.filter(status__exact='AV').order_by('?')[:10]

    context = {
        'HomePage' : True,
        'sliders' : sliders[1:sliders_count+1],
        'responsivesliders' : responsivesliders[1:responsivesliders_count+1],
        'banners' : banners,
        'banners_count' : banners_count,
        's_range' : range(sliders_count-1),
        'rs_range' : range(responsivesliders_count-1),
        'b_range' : range(banners_count),
        'first_slider' : sliders[0] if sliders else None,
        'first_rs' : responsivesliders[0] if responsivesliders else None,
        'sug_accounts' : accounts,
        'middle_banners' : middle_banner,
        'small_banners' : small_banner,
        'random_products': random_products,
    }
    return render(request, 'Codm/index.html', context)

def codm(request):
    q = request.GET.get('q')
    if q == None:
        accounts = models.Account.objects.filter(status__exact='available')
        q = 'available'
    else:
        accounts = models.Account.objects.filter(
            Q(status__exact=q) |
            Q(code__icontains=q) |
            Q(price__icontains=q)
        )
    if q == 'available' or q == 'sold' or q == 'w4p': 
        page = q
    else: 
        page = 'No-filter'
    context = {
        'accounts' : accounts,
        'main_filter' : page,
    }
    return render(request, 'Codm/products.html', context)
def account(request, gr, co):
    account = models.Account.objects.filter(group__exact=gr).get(code=co)
    seller = User.objects.get(username=account.seller.username)
    if gr == 'codm':
        codaccount = models.CodAccount.objects.get(account=account)
    links = account.link_set.all()
    images = account.image_set.all()
    fields = codaccount._meta.fields
    field_values = {}
    for field in fields:
        value = field.value_from_object(codaccount)
        field_values[field] = value
    context = {
        'account' : account,
        'codaccount' : codaccount,
        'links' : links,
        'l_count': links.count(),
        'images' : images,
        'Fields' : fields,
        'Values' : field_values,
        'seller' : seller,
    }
    return render(request, 'Codm/single-product.html', context)

def ListView(request, gr, page):
    group = models.Account.objects.filter(group__exact=gr, status__exact='available').order_by('-code')
    page = int(page)
    n = group.count()
    mini = 1
    if n >= 3:
        maxi = (n // 3) +2
        if page <= maxi:
            page_n = (page-1) * 3
            page_m = page_n + 3
            accounts = group[page_n:page_m]
        else: 
            raise Http404
    else:
        maxi = 1
        page = 1
        accounts = group
    context = {
        'accounts': accounts,
        'max_page' : maxi,
        'max_range' : range(page, maxi),
        'min_range' : range(1, page),
        'page' : page,
    }
    return render(request, 'Codm/products.html', context)

@login_required(login_url='Users:login')
def publish(request, co):
    availables = request.user.account_set.filter(status__exact='available').count()
    w4ps = request.user.account_set.filter(status__exact='w4p').count()
    if availables + w4ps >= 3:
        messages.error(request, 'شما نمی توانید بیش از 3 اکانت همزمان آگهی کنید. میتوانید آگهی های فعلی را پاک کنید تا بتوانید اکانت جدید آگهی کنید.')
        return redirect('Users:UserAccounts')
    account_number = models.Account.objects.all().count()+1001
    form = AccountForm()
    if co == 'Codm':
        form2 = CodAccountForm()
    videoform = AccountVideoForm()
    imageform1 = AccountImageForm()
    imageform2 = AccountImageForm()
    imageform3 = AccountImageForm()
    linkform = AccountLinkForm()
    if request.method == "POST":
        form = AccountForm(request.POST, request.FILES)
        if co == 'Codm':
            form2 = CodAccountForm(request.POST)
        videoform = AccountVideoForm(request.POST, request.FILES)
        imageform1 = AccountImageForm(request.POST, request.FILES)
        imageform2 = AccountImageForm(request.POST, request.FILES)
        imageform3 = AccountImageForm(request.POST, request.FILES)
        linkform = AccountLinkForm(request.POST)
        if form.is_valid():
            main_account = form.save(commit=False)
            main_account.seller = request.user
            main_account.code = account_number
            main_account.price += 50000
            main_account.save()
        if form2.is_valid():
            account = form2.save(commit=False)
            account.account = main_account
            account.save()
        if videoform.is_valid():
            videoaccount = videoform.save(commit=False)
            videoaccount.account = main_account
            videoaccount.save()
        if imageform1.is_valid():
            imageaccount1 = imageform1.save(commit=False)
            imageaccount2 = imageform2.save(commit=False)
            imageaccount3 = imageform3.save(commit=False)
            imageaccount1.account = main_account
            imageaccount2.account = main_account
            imageaccount3.account = main_account
            imageaccount1.save()
            imageaccount2.save()
            imageaccount3.save()
        if linkform.is_valid():
            link = linkform.save(commit=False)
            link.account = main_account
            link.save()
            return redirect('Codm:home')

    context = {
        'form' : form,
        'form2': form2,
        'videoform' : videoform,
        'imageform1' : imageform1,
        'imageform2' : imageform2,
        'imageform3' : imageform3,
        'linkform' : linkform,
        'code' : account_number,
    }

    return render(request, 'Codm/publish.html', context)

'''def publish_account(request):
    account_number = models.Account.objects.all().count()+1

    context = {
        'code' : account_number,
    }
    if request.method == "POST":
        Date = date.today()
        level = request.POST.get('level')
        image = request.POST.get('image')
        video = request.POST.get('video') if request.POST.get('video') != None else None
        activision = request.POST.get('activision')
        facebook = request.POST.get('facebook')
        gmail = request.POST.get('gmail')
        apple_id = request.POST.get('apple_id')
        line = request.POST.get('line')
        region = request.POST.get('region')
        multi_ranked = request.POST.get('multi_ranked')
        battle_ranked = request.POST.get('battle_ranked')
        battle_pass = request.POST.get('battle_pass')
        description = request.POST.get('description')
        price = int(request.POST.get('price'))
        final_price = price + 50000

        Account = models.Account(seller=request.user,
        level=level, 
        code=account_number, pub_date=Date, image=image,
        region=region, multi_ranked=multi_ranked,
        battle_ranked=battle_ranked,
        battle_pass=battle_pass,
        description=description,
        price=final_price)
        Account.save()
        return redirect('/Codm/Accounts/')
    return render(request, 'Codm/publishaccount.html', context)'''

Products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from . import models
from django.contrib.auth.decorators import login_required
from Codm.models import Cart
from django.http import HttpResponse
from django.contrib import messages

group_list = [
    'CP', 'COC', 'CR'
]
def ProductView(request, pname):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        products = group.product_set.all()

        context = {
            'group': group,
            'products': products,
        }
        return render (request, 'Products/index.html', context)

@login_required(login_url='Users:login')
def ProductAddCart(request, pname, pcode):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        product = group.product_set.get(code=pcode)
        if product:
            cart = request.user.cart
            cart.product.add(product)
            cart.final_price += product.price
            cart.save()
            messages.success(request, 'کالا به سبد خرید شما اضافه شد!')
            return redirect('Users:cart')
        else:
            messages.error(request, 'مشکلی پیش آمده! دوباره تلاش کنید')
            return redirect('Products:PV', pname)

@login_required(login_url='Users:login')
def ProductRemoveCart(request, pname, pcode):
    if pname in group_list:
        group = models.Group.objects.get(tag=pname)
        product = group.product_set.get(code=pcode)
        if product:
            cart = request.user.cart
            cart.final_price -= product.price
            cart.product.remove(product)
            cart.save()
            messages.success(request, 'کالا از سبد خرید شما حذف شد!')
            return redirect('Users:cart')
        else:
            messages.error(request, 'مشکلی پیش آمده! دوباره تلاش کنید')
            return redirect('Products:PV', pname)

Codm/templates/Codm/base.html
<!DOCTYPE html>
<html lang="fa">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#f7858d">
    <meta name="msapplication-navbutton-color" content="#f7858d">
    <meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
    <!--SiteLogo-->
    <link rel="icon" href="{% static 'assets/img/logo1.jpg' %}" type="image/logo" />
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/materialdesignicons.min.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <!-- Plugins -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap-slider.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/jquery.horizontalmenu.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/nouislider.min.css' %}">
    <!-- Main CSS File -->
    {% if request.session.mode == 'dark'  %}
    <link rel="stylesheet" href="{% static 'assets/css/main-dark.css' %}">
    {% elif request.session.mode == 'light'  %}
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    {% else %}
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" id="colorswitch">
    {% endif %}

    <link rel="stylesheet" href="{% static 'assets/css/colors/cyan-color.css' %}">
</head>
        
    <body>
        <div class="wrapper">
            <!-- Start header -->
            {% include 'Codm/navbar.html' %}
            <!-- End header -->
            <!-- Start main-content -->
            {% block content %}
            {% endblock %}
            <!-- End main-content -->
            {% include 'Codm/bottombar.html' %}
        </div>
    <!-- Core JS Files -->
    <script src="{% static 'assets/js/vendor/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <!-- Plugins -->
    <script src="{% static 'assets/js/vendor/bootstrap-slider.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/owl.carousel2.thumbs.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/nouislider.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.horizontalmenu.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/countdown.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/wNumb.js' %}"></script>
    <script src="{% static 'assets/js/vendor/ResizeSensor.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/theia-sticky-sidebar.min.js' %}"></script>
    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>

Codm/templates/Codm/codpage.html
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'codpage.css' %}" />
<div>
        <div class="top-container">
            <h2>Automatic Slideshow</h2>
            <p>Change image every 2 seconds:</p>

            <div class="slideshow-container">

            <div class="mySlides fade">
            <img src="{% static 'pictures/codm-banner.png' %}" style="width:100%;object-fit: cover;
            object-position: center;">
            </div>

            <div class="mySlides fade">
            <img src="{% static 'pictures/codm-poster.jpg' %}" style="width:100%;object-fit: cover;
            object-position: center;">
            </div>

            <div class="mySlides fade">
            <img src="{% static 'pictures/codm-wallpaper.jpg' %}" style="width:100%;object-fit: cover;
            object-position: center;">
            </div>

            </div>
            <br>

            <div style="text-align:center">
            <span class="dot"></span> 
            <span class="dot"></span> 
            <span class="dot"></span> 
            </div>

            <script>
            var slideIndex = 0;
            showSlides();

            function showSlides() {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";  
            }
            slideIndex++;
            if (slideIndex > slides.length) {slideIndex = 1}    
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex-1].style.display = "block";  
            dots[slideIndex-1].className += " active";
            setTimeout(showSlides, 3000); // Change image every 2 seconds
            }
            </script>
        </div>
        <div class="logo-container">
            <img src="{% static 'pictures/codm-logo.png' %}" alt="logo" />
        </div>
        <div class="main-container">
            <form method="get">
                <input type="text" placeholder="جست و جو کنید" name="q" />
                <input type="submit" value="جست و جو"/>
            </form>
            {% if main_filter != 'No-filter' %}
            <div id="main-filter">
                {% if main_filter == 'w4p' %}
                <h1>اکانت های آگهی شده و در لیست انتظار</h1>
                <a href="{% url 'Codm:Game' %}?q=available"><h3>اکانت های تایید شده و قابل خرید</h3></a>
                <a href="{% url 'Codm:Game' %}?q=sold"><h3>اکانت های فروخته شده</h3></a>
                {% elif main_filter == 'sold' %}
                <a href="{% url 'Codm:Game' %}?q=w4p"><h3>اکانت های آگهی شده و در لیست انتظار</h3></a>
                <a href="{% url 'Codm:Game' %}?q=available"><h3>اکانت های تایید شده و قابل خرید</h3></a>
                <h1>اکانت های فروخته شده</h1>
                {% else %}
                <a href="{% url 'Codm:Game' %}?q=w4p"><h3>اکانت های آگهی شده و در لیست انتظار</h3></a>
                <h1>اکانت های تایید شده و قابل خرید</h1>
                <a href="{% url 'Codm:Game' %}?q=sold"><h3>اکانت های فروخته شده</h3></a>
                {% endif %}
            </div>
            {% endif %}
            <a name="show"></a>
            <ul id="Ready"> 
                {% if accounts %}
                {% for account in accounts %}
                <li>
                    <div id="user-btn">
                    <a href="">{{account.seller}}@
                        <img style="height: 30px; width: 30px; border: solid 0.5px #33ccff; border-radius: 50%;" src="https://img.icons8.com/fluency/48/000000/test-account.png"/>
                    </a></div>
                    <a href="{% url 'Codm:account' account.code %}" target="_blank">
                        <div id="account-code">
                            <div>
                            شماره آگهی: {{account.code}}
                            </div>
                            {% if account.status == "available" %}
                            <div style="margin-right: 20px; background-color:#80ff80;">
                            موجود
                            </div>
                            {% elif account.status == "sold" %}
                            <div style="margin-right: 20px; background-color: #cc0000;
                            box-shadow: 0 0 8px 0#ff0000;">
                            فروخته شد
                            </div>
                            {% else %}
                            <div style="margin-right: 20px; background-color: #ffcc66;
                            box-shadow: 0 0 8px 0 rgb(255, 204, 0)">
                            در لیست انتظار
                            </div>
                            {% endif %} 
                        </div>
                    <div>
                        {% if account.image %}
                        <img src="{% static account.image.path %}" style="object-fit: cover;
                        object-position: center;"/>
                        {% else %}
                        <img src="{% static 'pictures/main-logo.jpg' %}" />
                        {% endif %}
                    </div>
                    </a>
                    <br />
                    <!--{{سیوها}}-->
                    {{account.price}}تومان<br /></a>
                    {% if account.status == 'available' %}
                    <a href="{% url 'Users:addtocart' account.code %}">افزودن به سبد خرید</a>
                    <a href="">ارسال پیام</a><br />
                    {% endif %}
                </li>
                {% endfor %}
                {% else %}
                <h1>متاسفانه اکانتی برای فروش نداریم:(</h1><br />
                <h2>بعدا سر بزنید</h2>
                {% endif %}
            </ul>
        </div>
</div>

Codm/templates/Codm/loading.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'prettify.min.js' %}"></script>
    <script src="{% static 'topbar.min.js' %}"></script>
    <script>
      var loadTime = window.performance.timing.domContentLoadedEventEnd;
      $(function() {
          prettyPrint()
          function resetToDefaults() {
            topbar.config({
              autoRun      : true,
              barThickness : 3,
              barColors    : {
                '0'      : '#00bcd4',
                '.25'    : '#00bcd4',
                '.50'    : '#00bcd4',
                '.75'    : '#00bcd4',
                '1.0'    : '#00bcd4'
              },
              shadowBlur   : 10,
              shadowColor  : 'rgba(0,   0,   0,   .6)',
              className    : 'topbar'
            })
          }

          // Page load
          resetToDefaults()
          topbar.show()
          setTimeout(function() {
            $('#main_content').fadeIn('slow')
            topbar.hide()
          }, loadTime)

          // Simple Demo
          $('#btnStartSimple').click(function() {
            resetToDefaults()
            topbar.show()
          })
          $('#btnStopSimple').click(function() {
            topbar.hide()  
          })
          /*
          // Advanced Demo
          $('#btnStartAdvanced').click(function() {
            resetToDefaults()
            topbar.config({
              autoRun      : false, 
              barThickness : 5,
              barColors    : {
                  '0'      : 'rgba(26,  188, 156, .7)',
                  '.3'     : 'rgba(41,  128, 185, .7)',
                  '1.0'    : 'rgba(231, 76,  60,  .7)'
              },
              shadowBlur   : 5,
              shadowColor  : 'rgba(0, 0, 0, .5)'
            })
            topbar.show();
            (function step() {
              setTimeout(function() {  
                if (topbar.progress('+.01') < 1) step()
              }, 16)
            })()
          })
          $('#btnStopAdvanced').click(function() {
            topbar.hide()  
          })*/
      })
    </script>
  </head>

  <body>
  </body>
</html>

Codm/templates/Codm/publish.html
<div style="position: absolute; top: 100%; left: 50%; transform:translate(-50%, -50%); direction: rtl;">
    <form method="POST">
        {% csrf_token %}
        کد آگهی شما: {{code}}
        {{form.as_p}}
        {{form2.as_p}}
        {{videoform.as_p}}
        {{imageform1.as_p}}
        {{imageform2.as_p}}
        {{imageform3.as_p}}
        {{linkform.as_p}}
        <input type="submit" value="آگهی اکانت"/><br />
    </form>
</div>