Codm/urls.py
from django.urls import re_path, path
from . import views
from uuid import uuid1
app_name = 'Codm'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/(?P<page>[0-9]{1,5})$', views.ListView, name="Game"),
    #path('<str:gr>/Accounts/Page<int:page>/', views.ListView, name="codm"),
    re_path(r'^(?P<gr>[a-z]{1,10})/Accounts/detail/(?P<co>[0-9]{1,5})/$', views.account, name="account"),
    path('<str:co>/Accounts/publish-account/', views.publish, name="publish-account"),
]

TSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Codm.urls')),
    path('user/', include('Users.urls')),
    path('products/', include('Products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import re_path
from . import views
from uuid import uuid1
app_name = 'Users'

id_list = str(uuid1()).split('-')
id1, *_, id2= id_list

urlpatterns = [
    re_path(r'^login/$', views.LoginFunc, name="login"),
    re_path(r'^logout/$', views.LogoutFunc, name="logout"),
    re_path(r'^registration/$', views.RegisterFunc, name="signup"),
    re_path(r'^welcome/$', views.WelcomeFunc, name="welcome"),

    re_path(r'^cart/details/$', views.user_cart, name="cart"),
    re_path(r'^cart/continue/UserInfo/$', views.cart_continue, name="cart_continue"),
    re_path(r'^cart/continue/UserInfo/SelectAccount/(?P<pr>[0-9]{1,10})/(?P<pk>[0-9]{1,10})$', views.add_account_product, name="add_account_product"),
    re_path(r'^cart/all/cart-end/success/{}/{}/$'.format(id1, id2), views.cart_success, name="cart-success"),
    re_path(r'^cart/success/finished/order/(?P<order>[0-9]{1,10})/(?P<order1>[0-9]{1,10})$', views.cart_finished, name="cart-finished"),
    re_path(r'^cart/details/shopping/render/ok$', views.shopping, name="shopping"),
    re_path(r'^addtocart/account/(?P<co>[0-9]{1,5})/$', views.addtocart, name="addtocart"),
    re_path(r'^removefromcart/account/(?P<co>[0-9]{1,5})/$', views.removefromcart, name="removefromcart"),

    re_path(r'^MyAccount/$', views.user_panel, name="UserPanel"),
    re_path(r'^MyAccount/Myinfo/Edit/$', views.user_edit, name="UserEdit"),
    re_path(r'^MyAccount/Orders/$', views.user_orders, name="UserOrders"),
    re_path(r'^MyAccount/Orders/OrderDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderDetail, name="UserOrderDetail"),
    re_path(r'^MyAccount/Orders/OrderAccountDetail/(?P<co>[0-9]{1,10})/$', views.UserOrderAccountDetail, name="UserOrderAccountDetail"),
    re_path(r'^MyAccount/Accounts/$', views.user_accounts, name="UserAccounts"),
    re_path(r'^MyAccount/Accounts/DeleteAccount/(?P<co>[0-9]{1,5})/$', views.user_delete_account, name="UserAccountDelete"),

    re_path(r'^SiteTheme/(?P<mode>[a-z]{1,10})/$', views.site_mode, name="ChangeMode"),
]

Products/models.py
from django.db import models
from Users.models import User

class Group(models.Model):
    tag = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='Products/media/Products/product-logos/', max_length=5000, null=True)
    background = models.ImageField(upload_to='Products/media/Products/product-backgrounds/', max_length=5000, null=True)
    description = models.TextField(max_length=900, null=True)

    facebook = models.BooleanField(default=False)
    gmail = models.BooleanField(default=False)
    apple = models.BooleanField(default=False)
    activition = models.BooleanField(default=True)
    supercell = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class EP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField()
    password = models.CharField(max_length=200)
    Ts = (
        ('activision' , 'اکتیویژن'),
        ('facebook' , 'فیسبوک'),
        ('gmail' , 'جیمیل'),
        ('apple' , 'اپل آی-دی'),
        ('supercell' , 'سوپرسل'),
    )
    Type = models.CharField(max_length=10, choices=Ts, default="Activision")

class Product(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    ep = models.ManyToManyField(EP, blank=True)

    code = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=900, null=True, blank=True)

    image = models.ImageField(upload_to='Products/media/Products/product_picture/{}/'.format(group.name), max_length=5000, null=True)

    S = (
        ('AV', 'Available'),
        ('NA', 'NotAvailable'),
    )
    status = models.CharField(max_length=2, choices=S, default='AV')

    price = models.IntegerField(default=30000)

    def __str__(self):
        return '{};{};{}تومان'.format(self.group, self.name, self.price)

Users/forms.py
from django import forms
from django.forms import ModelForm, widgets
from phonenumber_field.formfields import PhoneNumberField
from Codm import models
from . import models

class UserCreationForm(ModelForm):
    class Meta:
        model = models.User
        fields = ['name', 'username', 'phone', 'email', 'password']
        labels = {
            'name' : 'نام',
            'username' : 'نام کاربری',
            'phone' : 'تلفن همراه',
            'email' : 'ایمیل',
            'password' : 'رمز',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class':'input-ui pr-2'}),
            'username' : forms.TextInput(attrs={'class' : 'input-ui pr-2'}), 
            'phone' : forms.TextInput(attrs={'class' : 'input-ui pl-2 text-left dir-ltr'}),
            'email' : forms.EmailInput(attrs={'class':'input-ui pl-2 text-left dir-ltr'}),
        }

class UserEditionForm(ModelForm):
    class Meta:
        model = models.User
        fields = ['name', 'phone', 'email']
        labels = {
            'name' : 'نام',
            'phone' : 'تلفن همراه',
            'email' : 'ایمیل',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class':'input-ui pr-2'}),
            'phone' : forms.TextInput(attrs={'class' : 'input-ui pl-2 text-left dir-ltr'}),
            'email' : forms.EmailInput(attrs={'class':'input-ui pl-2 text-left dir-ltr'}),
        }

Codm/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from Products.models import Product
from . import models
from django.contrib import messages
from Codm.models import Order, Cart, Video
from django.db.models import Q
from Codm.forms import AccountForm, AccountLinkForm, CodAccountForm, AccountImageForm, AccountVideoForm
from django.http import Http404
#User Login
from django.contrib.auth.decorators import login_required
from django.conf import settings
User1 = settings.AUTH_USER_MODEL
from Users.models import User
#random
from random import randint

def home(request):
    sliders = models.Slider.objects.filter(show__exact=True)
    sliders_count = sliders.count()

    responsivesliders = models.ResponsiveSlider.objects.filter(show__exact=True)
    responsivesliders_count = responsivesliders.count()

    banners = models.Banner.objects.filter(show__exact=True).order_by('-code')
    banners_count = banners.count()

    middle_banner= banners.filter(Type__exact='middlebanner')[:2]
    small_banner = banners.filter(Type__exact='smallbanner')[:4]

    accounts = models.Account.objects.filter(status__exact='available', group__exact='codm').order_by('-code')[:10]
    random_products = Product.objects.filter(status__exact='AV').order_by('?')[:10]

    context = {
        'HomePage' : True,
        'sliders' : sliders[1:sliders_count+1],
        'responsivesliders' : responsivesliders[1:responsivesliders_count+1],
        'banners' : banners,
        'banners_count' : banners_count,
        's_range' : range(sliders_count-1),
        'rs_range' : range(responsivesliders_count-1),
        'b_range' : range(banners_count),
        'first_slider' : sliders[0] if sliders else None,
        'first_rs' : responsivesliders[0] if responsivesliders else None,
        'sug_accounts' : accounts,
        'middle_banners' : middle_banner,
        'small_banners' : small_banner,
        'random_products': random_products,
    }
    return render(request, 'Codm/index.html', context)

def codm(request):
    q = request.GET.get('q')
    if q == None:
        accounts = models.Account.objects.filter(status__exact='available')
        q = 'available'
    else:
        accounts = models.Account.objects.filter(
            Q(status__exact=q) |
            Q(code__icontains=q) |
            Q(price__icontains=q)
        )
    if q == 'available' or q == 'sold' or q == 'w4p': 
        page = q
    else: 
        page = 'No-filter'
    context = {
        'accounts' : accounts,
        'main_filter' : page,
    }
    return render(request, 'Codm/products.html', context)
def account(request, gr, co):
    account = models.Account.objects.filter(group__exact=gr).get(code=co)
    seller = User.objects.get(username=account.seller.username)
    if gr == 'codm':
        codaccount = models.CodAccount.objects.get(account=account)
    links = account.link_set.all()
    images = account.image_set.all()
    fields = codaccount._meta.fields
    field_values = {}
    for field in fields:
        value = field.value_from_object(codaccount)
        field_values[field] = value
    context = {
        'account' : account,
        'codaccount' : codaccount,
        'links' : links,
        'l_count': links.count(),
        'images' : images,
        'Fields' : fields,
        'Values' : field_values,
        'seller' : seller,
    }
    return render(request, 'Codm/single-product.html', context)

def ListView(request, gr, page):
    group = models.Account.objects.filter(group__exact=gr, status__exact='available').order_by('-code')
    page = int(page)
    n = group.count()
    mini = 1
    if n >= 3:
        maxi = (n // 3) +2
        if page <= maxi:
            page_n = (page-1) * 3
            page_m = page_n + 3
            accounts = group[page_n:page_m]
        else: 
            raise Http404
    else:
        maxi = 1
        page = 1
        accounts = group
    context = {
        'accounts': accounts,
        'max_page' : maxi,
        'max_range' : range(page, maxi),
        'min_range' : range(1, page),
        'page' : page,
    }
    return render(request, 'Codm/products.html', context)

@login_required(login_url='Users:login')
def publish(request, co):
    availables = request.user.account_set.filter(status__exact='available').count()
    w4ps = request.user.account_set.filter(status__exact='w4p').count()
    if availables + w4ps >= 3:
        messages.error(request, 'شما نمی توانید بیش از 3 اکانت همزمان آگهی کنید. میتوانید آگهی های فعلی را پاک کنید تا بتوانید اکانت جدید آگهی کنید.')
        return redirect('Users:UserAccounts')
    account_number = models.Account.objects.all().count()+1001
    form = AccountForm()
    if co == 'Codm':
        form2 = CodAccountForm()
    videoform = AccountVideoForm()
    imageform1 = AccountImageForm()
    imageform2 = AccountImageForm()
    imageform3 = AccountImageForm()
    linkform = AccountLinkForm()
    if request.method == "POST":
        form = AccountForm(request.POST, request.FILES)
        if co == 'Codm':
            form2 = CodAccountForm(request.POST)
        videoform = AccountVideoForm(request.POST, request.FILES)
        imageform1 = AccountImageForm(request.POST, request.FILES)
        imageform2 = AccountImageForm(request.POST, request.FILES)
        imageform3 = AccountImageForm(request.POST, request.FILES)
        linkform = AccountLinkForm(request.POST)
        if form.is_valid():
            main_account = form.save(commit=False)
            main_account.seller = request.user
            main_account.code = account_number
            main_account.price += 50000
            main_account.save()
        if form2.is_valid():
            account = form2.save(commit=False)
            account.account = main_account
            account.save()
        if videoform.is_valid():
            videoaccount = videoform.save(commit=False)
            videoaccount.account = main_account
            videoaccount.save()
        if imageform1.is_valid():
            imageaccount1 = imageform1.save(commit=False)
            imageaccount2 = imageform2.save(commit=False)
            imageaccount3 = imageform3.save(commit=False)
            imageaccount1.account = main_account
            imageaccount2.account = main_account
            imageaccount3.account = main_account
            imageaccount1.save()
            imageaccount2.save()
            imageaccount3.save()
        if linkform.is_valid():
            link = linkform.save(commit=False)
            link.account = main_account
            link.save()
            return redirect('Codm:home')

    context = {
        'form' : form,
        'form2': form2,
        'videoform' : videoform,
        'imageform1' : imageform1,
        'imageform2' : imageform2,
        'imageform3' : imageform3,
        'linkform' : linkform,
        'code' : account_number,
    }

    return render(request, 'Codm/publish.html', context)

'''def publish_account(request):
    account_number = models.Account.objects.all().count()+1

    context = {
        'code' : account_number,
    }
    if request.method == "POST":
        Date = date.today()
        level = request.POST.get('level')
        image = request.POST.get('image')
        video = request.POST.get('video') if request.POST.get('video') != None else None
        activision = request.POST.get('activision')
        facebook = request.POST.get('facebook')
        gmail = request.POST.get('gmail')
        apple_id = request.POST.get('apple_id')
        line = request.POST.get('line')
        region = request.POST.get('region')
        multi_ranked = request.POST.get('multi_ranked')
        battle_ranked = request.POST.get('battle_ranked')
        battle_pass = request.POST.get('battle_pass')
        description = request.POST.get('description')
        price = int(request.POST.get('price'))
        final_price = price + 50000

        Account = models.Account(seller=request.user,
        level=level, 
        code=account_number, pub_date=Date, image=image,
        region=region, multi_ranked=multi_ranked,
        battle_ranked=battle_ranked,
        battle_pass=battle_pass,
        description=description,
        price=final_price)
        Account.save()
        return redirect('/Codm/Accounts/')
    return render(request, 'Codm/publishaccount.html', context)'''

Users/templates/Panel/myaccounts.html
{% extends 'Panel/mypanel.html' %}
{% load static %}
{% load jalali_tags %}

{% block content %}
    <!-- Start Content -->
    <div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
        <div class="row">
            <div class="col-12">
                <p id="p">
                    تا حداکثر 3 اکانت می توانید در سایت آگهی کنید
                </p>
                <a href="{% url 'Codm:publish-account' 'Codm' %}">آگهی اکانت</a><br />
            </div>
                <div
                    class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                    <h2>آگهی های شما</h2>
                </div>
                <div class="dt-sl">
                    <div class="row">
                        {% for account in user_accounts %}
                        {% if account.status != 'canceled' %}
                        <div class="col-lg-12 col-md-12">
                            <div class="card-horizontal-product border-bottom rounded-0">
                                <div class="card-horizontal-product-thumb">
                                    <a href="{% url 'Codm:account' account.group account.code %}">
                                        <img {% if account.picture %} src="{{account.picture.url}}" {% else %}
                                        src="{% static 'assets/img/banner/codm1.jpg' %}"{% endif %}
                                        style="height: 200px; width: 200px; object-fit: cover; border-radius: 5px;
                                        object-position: center;" alt="Product Thumbnail">
                                    </a>
                                </div>
                                <div class="card-horizontal-product-content">
                                    <div class="card-horizontal-product-title">
                                        <a href="#">
                                            <h3>کد آگهی: {{account.code}}</h3>
                                        </a>
                                    </div>
                                    <div class="rating-stars">
                                        وضعیت آگهی: {{account.get_status_display}}
                                    </div>
                                    <div class="card-horizontal-product-price"><p id="p">
                                        قیمت شما: <span>{{account.price | add:'-50000'}} تومان</span><br />
                                        حق واسطه گری سایت: <span>50,000 تومان</span><br />
                                        قیمت نهایی آگهی در سایت: <span>{{account.price}} تومان</span></p>
                                    </div>
                                    {% if account.status != 'sold' %}
                                    <div class="card-horizontal-product-buttons">
                                        <a href="#" class="btn">ویرایش آگهی</a>
                                        <button class="remove-btn" data-toggle="modal"
                                        data-target="#remove-location">
                                            <i class="mdi mdi-trash-can-outline"></i>
                                        </button>
                                    </div>
                                    <div class="modal fade" id="remove-location" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title mb-3" id="exampleModalLabel">آیا مطمئن هستید که
                                                    این آگهی دیگر در سایت نمایش داده نشود؟</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="remodal-general-alert-button remodal-general-alert-button--cancel"
                                                    data-dismiss="modal">خیر</button>
                                                <a href="{% url 'Users:UserAccountDelete' account.code %}">
                                                <button type="button" 
                                                    class="remodal-general-alert-button remodal-general-alert-button--approve">بله</button></a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Users/templates/Panel/myinfo.html
{% extends 'Panel/mypanel.html' %}
{% load jalali_tags %}

{% block content %}
<div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
    <div class="row">
        <div class="col-xl-6 col-lg-12">
            <div class="px-3">
                <div
                    class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2">
                    <h2>اطلاعات شخصی</h2>
                </div>
                <div class="profile-section dt-sl">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>نام و نام خانوادگی:</span>
                            </div>
                            <div class="value-info">
                                <span>{{user.name}}</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>ایمیل:</span>
                            </div>
                            <div class="value-info">
                                <span>{{user.email}}</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>شماره همراه:</span>
                            </div>
                            <div class="value-info">
                                <span>0{{user_phone}}</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>تعداد خرید از سایت</span>
                            </div>
                            <div class="value-info">
                                <span>{{user.buys}}</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>تعداد فروش در سایت</span>
                            </div>
                            <div class="value-info">
                                <span>{{user.sells}}</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="label-info">
                                <span>شماره کارت:</span>
                            </div>
                            <div class="value-info">
                                <span>-</span>
                            </div>
                        </div>
                    </div>
                    <div class="profile-section-link">
                        <a href="{% url 'Users:UserEdit' %}" class="border-bottom-dt">
                            <i class="mdi mdi-account-edit-outline"></i>
                            ویرایش اطلاعات شخصی
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!--<div class="col-xl-6 col-lg-12">
            <div class="px-3">
                <div
                    class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2">
                    <h2>لیست آخرین علاقه‌مندی‌ها</h2>
                </div>
                <div class="profile-section dt-sl">
                    <ul class="list-favorites">
                        <li>
                            <a href="#">
                                <img src="./assets/img/products/016.jpg" alt="">
                                <span>کت مردانه مجلسی مدل k-m-5500</span>
                            </a>
                            <button>
                                <i class="mdi mdi-trash-can-outline"></i>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="./assets/img/products/020.jpg" alt="">
                                <span>کت مردانه مجلسی مدل k-m-5640</span>
                            </a>
                            <button>
                                <i class="mdi mdi-trash-can-outline"></i>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="./assets/img/products/017.jpg" alt="">
                                <span>کت مردانه مجلسی مدل k-m-5110</span>
                            </a>
                            <button>
                                <i class="mdi mdi-trash-can-outline"></i>
                            </button>
                        </li>
                    </ul>
                    <div class="profile-section-link">
                        <a href="#" class="border-bottom-dt">
                            <i class="mdi mdi-square-edit-outline"></i>
                            مشاهده و ویرایش لیست مورد علاقه
                        </a>
                    </div>
                </div>
            </div>
        </div>-->
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <div
                class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                <h2>آخرین سفارش‌ها</h2>
            </div>
            <div class="dt-sl">
                <div class="table-responsive">
                    <table class="table table-order">
                        <thead>
                            <tr>
                                <th>شماره سفارش</th>
                                <th>شماره فاکتور</th>
                                <th>تاریخ ثبت سفارش</th>
                                <th>مبلغ کل</th>
                                <th>وضعیت سفارش</th>
                                <th>مشاهده جزئیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <td>{{order.order_number}}</td>
                                <td>{{order.factor_number}}</td>
                                <td>14{{order.date|to_jalali:'%y/%m/%d'}}</td>
                                <td>{{order.final_price}} تومان</td>
                                <td>{{order.get_status_display}}</td>
                                <td class="details-link">
                                    <a href="{% url 'Users:UserOrderDetail' order.order_number %}">
                                        <i class="mdi mdi-chevron-left"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td class="link-to-orders" colspan="7"><a href="{% url 'Users:UserOrders' %}">مشاهده لیست سفارش
                                        ها</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Users/templates/Panel/myorders.html
{% extends 'Panel/mypanel.html' %}
{% load jalali_tags %}

{% block content %}
<!-- Start Content -->
<div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
    <div class="row">
        <div class="col-12">
            <div
                class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                <h2>همه سفارش‌ها</h2>
            </div>
            <div class="dt-sl">
                <div class="table-responsive">
                    <table class="table table-order">
                        <thead>
                            <tr>
                                <th>شماره سفارش</th>
                                <th>شماره فاکتور</th>
                                <th>تاریخ ثبت سفارش</th>
                                <th>مبلغ کل</th>
                                <th>وضعیت سفارش</th>
                                <th>مشاهده جزئیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in user_orders %}
                            <tr>
                                <td>{{order.order_number}}</td>
                                <td>{{order.factor_number}}</td>
                                <td>14{{order.date|to_jalali:'%y/%m/%d'}}</td>
                                <td>{{order.final_price}} تومان</td>
                                <td>{{order.get_status_display}}</td>
                                <td class="details-link">
                                    <a href="{% url 'Users:UserOrderDetail' order.order_number %}">
                                        <i class="mdi mdi-chevron-left"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% for order in user_order_accounts %}
                            <tr>
                                <td>{{order.order_number}}</td>
                                <td>{{order.factor_number}}</td>
                                <td>14{{order.date|to_jalali:'%y/%m/%d'}}</td>
                                <td>{{order.final_price}} تومان</td>
                                <td>{{order.get_status_display}}</td>
                                <td class="details-link">
                                    <a href="{% url 'Users:UserOrderAccountDetail' order.order_number %}">
                                        <i class="mdi mdi-chevron-left"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Content -->
</div>
{% endblock %}

Users/templates/Panel/panel.html
<html>
<head>

</head>
<body style="direction: rtl;">
<div style="float:right; margin-left: 50px;">
    <div>
        <h1>{{user.name}}</h1> <br/>
        <h2>!به پنل کاربریتان خوش آمدید</h2>
    </div>
    <ul>
        <li><a href="{% url 'Users:UserPanel' %}">اطلاعات من</a></li>
        <li><a href="{% url 'Users:cart' %}">سبد خرید من</a></li>
        <li><a href="{% url 'Users:UserAccounts' %}">اکانت های من</a></li>
        <li><a href="#">سفارشات من</a></li>
        <li><a href="{% url 'Users:logout' %}">خروج از حساب</a></li>
    </ul>
</div>
<div style="float:right">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>